Exception on /vehicle [GET]
Traceback (most recent call last):
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\A.py", line 103, in vehicle
    return render_template('vehicle.html', vehicles=vehicles)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\templates\vehicle.html", line 18, in top-level template code
    <a href="{{ url_for('purchase') }}">Purchase</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'purchase'. Did you forget to specify values ['vehicle_id']?
Exception on /vehicle [GET]
Traceback (most recent call last):
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\Honey.py", line 90, in vehicle
    return render_template('vehicle.html', vehicle=vehicles)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\templates\vehicle.html", line 18, in top-level template code
    <a href="{{ url_for('purchase') }}">Purchase</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Digital\Desktop\Phase1 Honey Motors\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'purchase'. Did you mean 'profile' instead?
